// Generated by CoffeeScript 1.7.1
(function() {
  var assert;

  assert = require("assert");

  describe("Create paragraph", function() {
    describe("test 1", function() {
      it("should create a paragraph with given text", function() {
        assert.equal("2", "2");
      });
    });
  });

  describe("String from XML");

}).call(this);

//# sourceMappingURL=clientTests.map
