// Generated by CoffeeScript 1.7.1

/*
Module dependencies.
 */

(function() {
  var app, db, express, http, mongoose, passport, path, routes;

  express = require('express');

  routes = require('./routes');

  http = require('http');

  path = require('path');

  mongoose = require('mongoose');

  passport = require('./routes/user');

  app = express();

  mongoose.connect('mongodb://localhost/test');

  db = mongoose.connection;

  db.on('error', console.error.bind(console, 'connection error:'));

  db.once('open', function() {
    return console.log('DB connection opened');
  });

  app.set('layout', 'layouts/main');

  app.set('partials', {
    welcome: 'partials/welcome',
    results: 'partials/results',
    csv: 'partials/csv',
    scripts: 'partials/scripts',
    model: 'partials/model',
    tutorial: 'partials/tutorial',
    dashboard: 'partials/dashboard',
    functions: 'partials/functions',
    visualization: 'partials/visualization',
    uploadCSV: 'partials/uploadCSV',
    unzip: 'partials/unzip'
  });

  app.engine('html', require("hogan-express"));

  app.enable('view cache');

  app.configure(function() {
    app.set("port", process.env.PORT || 3000);
    app.set("views", __dirname + "/views");
    app.set("view engine", "html");
    app.use(express.favicon());
    app.use(express.logger("dev"));
    app.use(express.json());
    app.use(express.urlencoded());
    app.use(express.methodOverride());
    app.use(express.cookieParser('csci3601'));
    app.use(express.session({
      cookie: {
        maxAge: 3600000
      },
      secret: 'csci3601'
    }));
    app.use(passport.initialize());
    app.use(passport.session());
    return app.use(app.router);
  });

  app.use(express["static"](path.join(__dirname, "public")));

  app.use(express["static"](path.join(__dirname, 'bower_components')));

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  app.get("/", routes.index);

  app.get("/dash", routes.dash);

  app.get("/model-maker", routes.modelMaker);

  app.get("/failed", routes.failed);

  app.get("/user", routes.user);

  app.get("/login", routes.login);

  app.get("/newUser", routes.newUser);

  app.get("/logout", routes.logout);

  app.get("/account", routes.account);

  app.post("/addPrompt", routes.addPrompt);

  app.post('/create', routes.create);

  app.post('/updatePassword', routes.updatePassword);

  app.put('/addPrompt', routes.addPrompt);

  app.post('/', passport.authenticate('local-login', {
    failureRedirect: '/failed',
    successRedirect: '/dash'
  }));

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);

//# sourceMappingURL=app.map
