// Generated by CoffeeScript 1.7.1

/*
Module dependencies.
 */

(function() {
  var app, db, express, http, mongoose, passport, path, routes;

  express = require('express');

  routes = require('./routes');

  http = require('http');

  path = require('path');

  mongoose = require('mongoose');

  passport = require('./routes/user');

  app = express();

  mongoose.connect('mongodb://localhost/test');

  db = mongoose.connection;

  db.on('error', console.error.bind(console, 'connection error:'));

  db.once('open', function() {
    return console.log('DB connection opened');
  });

  app.set('layout', 'layouts/main');

  app.set('partials', {
    welcome: 'partials/welcome',
    results: 'partials/results',
    csv: 'partials/csv',
    navbar: 'partials/navbar',
    scripts: 'partials/scripts',
    model: 'partials/model'
  });

  app.engine('html', require("hogan-express"));

  app.enable('view cache');

  app.configure(function() {
    app.set("port", process.env.PORT || 3000);
    app.set("views", __dirname + "/views");
    app.set("view engine", "html");
    app.use(express.favicon());
    app.use(express.logger("dev"));
    app.use(express.json());
    app.use(express.urlencoded());
    app.use(express.methodOverride());
    app.use(express.cookieParser('csci3601'));
    app.use(express.session({
      secret: 'csci3601'
    }));
    app.use(passport.initialize());
    app.use(passport.session());
    return app.use(app.router);
  });

  app.use(express["static"](path.join(__dirname, "public")));

  app.use(express["static"](path.join(__dirname, 'bower_components')));

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  app.get("/", routes.index);

  app.get("/results", routes.results);

  app.get("/csvPage", routes.csvPage);

  app.get("/modelPage", routes.modelPage);

  app.get("/users", routes.list);

  app.get("/failed", routes.failed);

  app.get("/user", routes.user);

  app.post('/', passport.authenticate('local-login', {
    failureRedirect: '/failed',
    successRedirect: '/user'
  }));

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);

//# sourceMappingURL=app.map
