// Generated by CoffeeScript 1.7.1
(function() {
  exports.index = function(req, res) {
    console.log('inside index');
    res.locals = {
      title: 'LightSide',
      header: 'LightSide Test Page'
    };
    return res.render('index');
  };

  exports.results = function(req, res) {
    console.log('inside results');
    res.locals = {
      title: 'LightSide',
      header: 'LightSide Results Page'
    };
    return res.render('index');
  };

  exports.csvPage = function(req, res) {
    res.locals = {
      title: 'LightSide',
      header: 'LightSide CSV Upload Page'
    };
    return res.render('index');
  };

  exports.list = function(req, res) {
    return res.send("respond with a resource");
  };

}).call(this);

//# sourceMappingURL=index.map
