// Generated by CoffeeScript 1.6.3
/*
Module dependencies.
*/


(function() {
  var express, routes;

  express = require("express");

  routes = require("./routes");

  exports.list = function(req, res) {
    res.send("respond with a resource");
  };

}).call(this);

/*
//@ sourceMappingURL=user.map
*/
