// Generated by CoffeeScript 1.6.3
(function() {
  var Schema, mongoose, user, userSchema;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  userSchema = mongoose.Schema({
    password: String,
    email: String,
    firstName: String,
    surname: String,
    promptArray: [String]
  });

  user = mongoose.model('user', userSchema);

  module.exports = {
    user: user
  };

}).call(this);

/*
//@ sourceMappingURL=userSchema.map
*/
